### PR TITLE
finish Sprint6

### PR DESCRIPTION
**Pull request by bebaoboy**

### CODE REVIEW

**Comment by bebaoboy** [comment]
need to do get favorite project api

**Comment by bebaoboy** [comment]
Looking good, pls merge

**Review by vhhoang20 — APPROVED** [review]

**Review by quanJonathan — APPROVED** [review]
- There are some adjustment could be made for the app theme. Consider change it in next sprint.
- As we have change from flushbar to toastify, some changes have to be made for some files.
- The spacing between text field and label should be increase.
- Increase fetching time of background fetch.
-

**Comment by bebaoboy** [comment]
> - There are some adjustment could be made for the app theme. Consider change it in next sprint.
> - As we have change from flushbar to toastify, some changes have to be made for some files.
> - The spacing between text field and label should be increase.
> - Increase fetching time of background fetch.
> - 

Will fix in next sprint ^^

**Pull request merged**
